services:
  Customer.CustomerRepository:
    class: ../../../Contexts/Customer/Customer/infrastructure/CustomerRepositoryFirebase
    arguments: []

  Customer.CustomerCreate:
    class: ../../../Contexts/Customer/Customer/application/create/CustomerCreate
    arguments: ['@Customer.CustomerRepository', '@Shared.EventBus']

  Customer.CustomerCreateCommandHandler:
    class: ../../../Contexts/Customer/Customer/application/create/CustomerCreateCommandHandler
    arguments: ['@Customer.CustomerCreate']
    tags:
      - { name: 'commandHandler' }

  Customer.CustomerCreateController:
    class: ../../../Apps/Customer/controllers/CustomerCreateController
    arguments: ['@Shared.CommandBus']

  Customer.CustomerProfile:
    class: ../../../Contexts/Customer/Customer/application/profile/CustomerProfile
    arguments: ['@Customer.CustomerRepository']

  Customer.CustomerProfileQueryHandler:
    class: ../../../Contexts/Customer/Customer/application/profile/CustomerProfileQueryHandler
    arguments: ['@Customer.CustomerProfile']
    tags:
      - { name: 'queryHandler' }

  Customer.CustomerProfileController:
    class: ../../../Apps/Customer/controllers/CustomerProfileController
    arguments: ['@Shared.QueryBus']

  Customer.CustomerUpdate:
    class: ../../../Contexts/Customer/Customer/application/update/CustomerUpdate
    arguments: ['@Customer.CustomerRepository']

  Customer.CustomerUpdateCommandHandler:
    class: ../../../Contexts/Customer/Customer/application/update/CustomerUpdateCommandHandler
    arguments: ['@Customer.CustomerUpdate']
    tags:
      - { name: 'commandHandler' }

  Customer.CustomerUpdateController:
    class: ../../../Apps/Customer/controllers/CustomerUpdateController
    arguments: ['@Shared.CommandBus']

