services:
  Notification.EmailSenderService:
    class: ../../../Contexts/Notifications/infrastructure/EmailSenderService
    arguments: []

  Notification.SendEmailCustomerRewardPoint:
    class: ../../../Contexts/Notifications/application/sendEmailCustomerRewardPoint/SendEmailCustomerRewardPointIncremented
    arguments: ['@Notification.EmailSenderService']

  Notification.SendEmailOnCustomerRewardPoint:
    class: ../../../Contexts/Notifications/application/sendEmailCustomerRewardPoint/SendEmailOnCustomerRewardPointIncremented
    arguments: ["@Notification.SendEmailCustomerRewardPoint"]
    tags:
      - { name: 'domainEventSubscriber' }

  Notification.SendEmailCustomerCreated:
    class: ../../../Contexts/Notifications/application/sendEmailCustomerCreated/SendEmailCustomerCreated
    arguments: ['@UserRecord.UserRecordRepository', '@Notification.EmailSenderService']

  Notification.SendEmailOnCustomerCreated:
    class: ../../../Contexts/Notifications/application/sendEmailCustomerCreated/SendEmailOnCustomerCreated
    arguments: ["@Notification.SendEmailCustomerCreated"]
    tags:
      - { name: 'domainEventSubscriber' }