services:
  ServiceProvider.ServiceProviderRepository:
    class: ../../../Contexts/ServiceProvider/infrastructure/ServiceProviderRepositoryFirebase
    arguments: []

  ServiceProvider.ServiceProviderCreate:
    class: ../../../Contexts/ServiceProvider/application/create/ServiceProviderCreate
    arguments: ['@ServiceProvider.ServiceProviderRepository','@UserRecord.UserRecordRepository', '@Shared.EventBus']
  
  ServiceProvider.ServiceProviderCreateCommandHandler:
    class: ../../../Contexts/ServiceProvider/application/create/ServiceProviderCreateCommandHandler
    arguments: ['@ServiceProvider.ServiceProviderCreate']
    tags:
      - { name: 'commandHandler' }

  ServiceProvider.ServiceProviderCreateController:
    class: ../../../Apps/ServiceProvider/controllers/ServiceProviderCreateController
    arguments: ['@Shared.CommandBus']

  ServiceProvider.ServiceProviderUpdate:
    class: ../../../Contexts/ServiceProvider/application/update/ServiceProviderUpdate
    arguments: ['@ServiceProvider.ServiceProviderRepository', '@Shared.EventBus']

  ServiceProvider.ServiceProviderUpdateCommandHandler:
    class: ../../../Contexts/ServiceProvider/application/update/ServiceProviderUpdateCommandHandler
    arguments: ['@ServiceProvider.ServiceProviderUpdate']
    tags:
      - { name: 'commandHandler' }

  ServiceProvider.ServiceProviderUpdateController:
    class: ../../../Apps/ServiceProvider/controllers/ServiceProviderUpdateController
    arguments: ['@Shared.CommandBus']

  ServiceProvider.ServiceProviderProfile:
    class: ../../../Contexts/ServiceProvider/application/profile/ServiceProviderProfile
    arguments: ['@ServiceProvider.ServiceProviderRepository', '@UserRecord.UserRecordRepository']

  ServiceProvider.ServiceProviderQueryHandler:
    class: ../../../Contexts/ServiceProvider/application/profile/ServiceProviderProfileQueryHandler
    arguments: ['@ServiceProvider.ServiceProviderProfile']
    tags:
      - { name: 'queryHandler' }

  ServiceProvider.ServiceProviderProfileController:
    class: ../../../Apps/ServiceProvider/controllers/ServiceProviderProfileController
    arguments: ['@Shared.QueryBus']

