services:
  ServiceProvider.ServiceProviderRepository:
    class: ../../../Contexts/ServiceProvider/ServiceProvider/infrastructure/ServiceProviderRepositoryFirebase
    arguments: []

  ServiceProvider.ServiceProviderCreate:
    class: ../../../Contexts/ServiceProvider/ServiceProvider/application/create/ServiceProviderCreate
    arguments: ['@ServiceProvider.ServiceProviderRepository',  '@Shared.EventBus']


  ServiceProvider.ServiceProviderCreateCommandHandler:
    class: ../../../Contexts/ServiceProvider/ServiceProvider/application/create/ServiceProviderCreateCommandHandler
    arguments: ['@ServiceProvider.ServiceProviderCreate']
    tags:
      - { name: 'commandHandler' }

  ServiceProvider.ServiceProviderCreateController:
    class: ../../../Apps/ServiceProvider/controllers/ServiceProviderCreateController
    arguments: ['@Shared.CommandBus']

  ServiceProvider.ServiceProviderProfile:
    class: ../../../Contexts/ServiceProvider/ServiceProvider/application/profile/ServiceProviderProfile
    arguments: ['@ServiceProvider.ServiceProviderRepository']

  ServiceProvider.ServiceProviderQueryHandler:
    class: ../../../Contexts/ServiceProvider/ServiceProvider/application/profile/ServiceProviderProfileQueryHandler
    arguments: ['@ServiceProvider.ServiceProviderProfile']
    tags:
      - { name: 'queryHandler' }

  ServiceProvider.ServiceProviderProfileController:
    class: ../../../Apps/ServiceProvider/controllers/ServiceProviderProfileController
    arguments: ['@Shared.QueryBus']

