services:
  Backoffice.customer.BackofficeCustomerRepositoryFirebase:
    class: ../../../Contexts/Backoffice/Customer/infrastructure/BackofficeCustomerRepositoryFirebase
    arguments: []

  Backoffice.customer.BackofficeCustomerList:
    class: ../../../Contexts/Backoffice/Customer/application/list/BackofficeCustomerList
    arguments: ['@Backoffice.customer.BackofficeCustomerRepositoryFirebase']

  Backoffice.customer.BackofficeCustomerListQueryHandler:
    class: ../../../Contexts/Backoffice/Customer/application/list/BackofficeCustomerListQueryHandler
    arguments: ['@Backoffice.customer.BackofficeCustomerList']
    tags:
      - { name: 'queryHandler' }

  Backoffice.customer.BackofficeCustomerListController:
    class: ../../backoffice/customer/controller/BackofficeCustomerListController
    arguments: ['@Shared.QueryBus']

  Backoffice.seller.BackofficeSellerRepositoryFirebase:
    class: ../../../Contexts/Backoffice/Seller/infrastructure/BackofficeSellerRepositoryFirebase
    arguments: []

  Backoffice.seller.BackofficeSellerList:
    class: ../../../Contexts/Backoffice/Seller/application/list/BackofficeSellerList
    arguments: ['@Backoffice.seller.BackofficeSellerRepositoryFirebase']

  Backoffice.seller.BackofficeSellerListQueryHandler:
    class: ../../../Contexts/Backoffice/Seller/application/list/BackofficeSellerListQueryHandler
    arguments: ['@Backoffice.seller.BackofficeSellerList']
    tags:
      - { name: 'queryHandler' }

  Backoffice.seller.BackofficeSellerListController:
    class: ../../backoffice/seller/controller/BackofficeSellerListController
    arguments: ['@Shared.QueryBus']