services:
  Authentication.AuthenticationRepositoryFirebase:
    class: ../../../Contexts/Authentication/infrastructure/AuthenticationFirebaseRepository
    arguments: []

  Authentication.AuthenticationSignIn:
    class: ../../../Contexts/Authentication/application/AuthenticationSignIn
    arguments: ['@Authentication.AuthenticationRepositoryFirebase', '@Shared.EventBus']

  Authentication.AuthenticationSignInController:
    class: ../../../Apps/Authentication/controllers/AuthenticationSignInController
    arguments: ['@Authentication.AuthenticationSignIn']

  Authentication.AuthenticationSignOut:
    class: ../../../Contexts/Authentication/application/AuthenticationSignOut
    arguments: ['@Authentication.AuthenticationRepositoryFirebase']

  Authentication.AuthenticationSignOutController:
    class: ../../../Apps/Authentication/controllers/AuthenticationSignOutController
    arguments: ['@Authentication.AuthenticationSignOut']