imports: 
  - { resource: ./Shared/application.yaml }
  - { resource: ./Customer/application.yaml }
  - { resource: ./Backoffice/application.yaml}
  - { resource: ./Seller/application.yaml }
  - { resource: ./ServiceProvider/application.yaml }
  - { resource: ./UserRecord/application.yaml}
  - { resource: ./Authentication/application.yaml}
  - { resource: ./CustomerRewardPoint/application.yaml}
  - { resource: ./Notifications/application.yaml}
  - { resource: ./Contract/application.yaml}