services:
  Contract.ContractRepository:
    class: ../../../Contexts/Contract/infrastructure/ContractRepositoryFirebase
    arguments: []

  Contract.ContractCreate:
    class: ../../../Contexts/Contract/application/create/ContractCreate
    arguments: ['@UserRecord.UserRecordRepository', '@Contract.ContractRepository']
  
  Contract.ContractCreateCommandHandler:
    class: ../../../Contexts/Contract/application/create/ContractCreateCommandHandler
    arguments: ['@Contract.ContractCreate']
    tags:
      - { name: 'commandHandler' }

  Contract.ContractCreateController:
    class: ../../../Apps/Contract/controllers/ContractCreateController
    arguments: ['@Shared.CommandBus']

  Contract.ContractReject:
    class: ../../../Contexts/Contract/application/contractReject/ContractReject
    arguments: ['@Contract.ContractRepository']

  Contract.ContractRejectCommandHandler:
    class: ../../../Contexts/Contract/application/contractReject/ContractRejectCommandHandler
    arguments: ['@Contract.ContractReject']
    tags:
      - { name: 'commandHandler' }

  Contract.ContractRejectController:
    class: ../../../Apps/Contract/controllers/ContractRejectController
    arguments: ['@Shared.CommandBus']

  Contract.ContractApprove:
    class: ../../../Contexts/Contract/application/contractApprove/ContractApprove
    arguments: ['@Contract.ContractRepository']

  Contract.ContractApproveCommandHandler:
    class: ../../../Contexts/Contract/application/contractApprove/ContractApproveCommandHandler
    arguments: ['@Contract.ContractApprove']
    tags:
      - { name: 'commandHandler' }

  Contract.ContractApproveController:
    class: ../../../Apps/Contract/controllers/ContractApproveController
    arguments: ['@Shared.CommandBus']

  Contract.ContractUnverified:
    class: ../../../Contexts/Contract/application/unverified/ContractUnverified
    arguments: ['@Contract.ContractRepository']

  Contract.ContractUnverifiedQueryHandler:
    class: ../../../Contexts/Contract/application/unverified/ContractUnverifiedQueryHandler
    arguments: ['@Contract.ContractUnverified']
    tags:
      - { name: 'queryHandler' }

  Contract.ContractUnverifiedController:
    class: ../../../Apps/Contract/controllers/ContractUnverifiedController
    arguments: ['@Shared.QueryBus']