services:
  UserRecord.UserRecordRepository:
    class: ../../../Contexts/UserRecord/infrastructure/UserRecordRepositoryFirebase
    arguments: []

  UserRecord.UserRecordCreate:
    class: ../../../Contexts/UserRecord/application/accountCreate/UserRecordCreate
    arguments: ['@UserRecord.UserRecordRepository']

  UserRecord.UserRecordCreateCommandHandler:
    class: ../../../Contexts/UserRecord/application/accountCreate/UserRecordCreateCommandHandler
    arguments: ['@UserRecord.UserRecordCreate']
    tags:
      - { name: 'commandHandler' }

  UserRecord.UserRecordUpdate:
    class: ../../../Contexts/UserRecord/application/accountUpdate/UserRecordUpdate
    arguments: ['@UserRecord.UserRecordRepository']

  UserRecord.UserRecordUpdateCommandHandler:
    class: ../../../Contexts/UserRecord/application/accountUpdate/UserRecordUpdateCommandHandler
    arguments: ['@UserRecord.UserRecordUpdate']
    tags:
      - { name: 'commandHandler' }

  UserRecord.UserRecordProfile:
    class: ../../../Contexts/UserRecord/application/profile/UserRecordProfile
    arguments: ['@UserRecord.UserRecordRepository']
    
  UserRecord.UserRecordProfileQueryHandler:
    class: ../../../Contexts/UserRecord/application/profile/UserRecordProfileQueryHandler
    arguments: ['@UserRecord.UserRecordProfile']
    tags: 
      - { name: 'queryHandler' }

  UserRecord.UserRecordProfileController:
    class: ../../../Apps/UserRecord/controllers/UserRecordProfileController
    arguments: ['@Shared.QueryBus']

  UserRecord.UserRecordRemove:
    class: ../../../Contexts/UserRecord/application/accountRemove/UserRecordRemove
    arguments: ['@UserRecord.UserRecordRepository']

  UserRecord.UserRecordRemoveCommandHandler:
    class: ../../../Contexts/UserRecord/application/accountRemove/UserRecordRemoveCommandHandler
    arguments: ['@UserRecord.UserRecordRemove']
    tags:
      - { name: 'commandHandler' }

  UserRecord.UserRecordDisable:
    class: ../../../Contexts/UserRecord/application/accountDisable/UserRecordDisable
    arguments: ['@UserRecord.UserRecordRepository']

  UserRecord.UserRecordDisableOnServiceProviderCreated:
    class: ../../../Contexts/UserRecord/application/accountDisable/UserRecordDisableOnServiceProviderCreated
    arguments: ["@UserRecord.UserRecordDisable"]
    tags:
      - { name: 'domainEventSubscriber' }

  UserRecord.UserRecordEnable:
    class: ../../../Contexts/UserRecord/application/accountEnable/UserRecordEnable
    arguments: ['@UserRecord.UserRecordRepository']

  UserRecord.UserRecordResetPassword:
    class: ../../../Contexts/UserRecord/application/accountResetPassword/UserRecordResetPassword
    arguments: ['@UserRecord.UserRecordRepository']
  
  UserRecord.UserRecordResetPasswordCommandHandler:
    class: ../../../Contexts/UserRecord/application/accountResetPassword/UserRecordResetPasswordCommandHandler
    arguments: ['@UserRecord.UserRecordResetPassword']
    tags:
      - { name: 'commandHandler' }

  UserRecord.UserRecordResetPasswordController:
    class: ../../../Apps/UserRecord/controllers/UserRecordResetPasswordController
    arguments: ['@Shared.CommandBus']