services:
  UserRecord.UserRecordRepository:
    class: ../../../Contexts/UserRecord/infrastructure/UserRecordRepositoryFirebase
    arguments: []

  UserRecord.UserRecordCreate:
    class: ../../../Contexts/UserRecord/application/Create/UserRecordCreate
    arguments: ['@UserRecord.UserRecordRepository']


  UserRecord.UserRecordCreateCommandHandler:
    class: ../../../Contexts/UserRecord/application/Create/UserRecordCreateCommandHandler
    arguments: ['@UserRecord.UserRecordCreate']
    tags:
      - { name: 'commandHandler' }

  UserRecord.UserRecordUpdate:
    class: ../../../Contexts/UserRecord/application/Update/UserRecordUpdate
    arguments: ['@UserRecord.UserRecordRepository']

  UserRecord.UserRecordUpdateTransaction:
    class: ../../../Contexts/UserRecord/application/UpdateTransaction/UserRecordUpdateTransaction
    arguments: ['@UserRecord.UserRecordRepository']

  UserRecord.UserRecordUpdateCommandHandler:
    class: ../../../Contexts/UserRecord/application/Update/UserRecordUpdateCommandHandler
    arguments: ['@UserRecord.UserRecordUpdate']
    tags:
      - { name: 'commandHandler' }

  UserRecord.UserRecordProfile:
    class: ../../../Contexts/UserRecord/application/Profile/UserRecordProfile
    arguments: ['@UserRecord.UserRecordRepository']
    
  UserRecord.UserRecordProfileQueryHandler:
    class: ../../../Contexts/UserRecord/application/Profile/UserRecordProfileQueryHandler
    arguments: ['@UserRecord.UserRecordProfile']
    tags: 
      - { name: 'queryHandler' }

  UserRecord.UserRecordProfileController:
    class: ../../../Apps/UserRecord/controllers/UserRecordProfileController
    arguments: ['@Shared.QueryBus']

  UserRecord.UserRecordProfileCollection:
    class: ../../../Contexts/UserRecord/application/ProfileCollection/UserRecordProfileCollection
    arguments: ['@UserRecord.UserRecordRepository']

  UserRecord.UserRecordDelete:
    class: ../../../Contexts/UserRecord/application/Delete/UserRecordDelete
    arguments: ['@UserRecord.UserRecordRepository']

  UserRecord.UserRecordDeleteCommandHandler:
    class: ../../../Contexts/UserRecord/application/Delete/UserRecordDeleteCommandHandler
    arguments: ['@UserRecord.UserRecordDelete']
    tags:
      - { name: 'commandHandler' }

  # UserRecord.UserRecordDisableOnServiceProviderCreated:
  #   class: ../../../Contexts/UserRecord/application/Disable/UserRecordDisableOnServiceProviderCreated
  #   arguments: ["@UserRecord.UserRecordDisable"]
  #   tags:
  #     - { name: 'domainEventSubscriber' }

  UserRecord.UserRecordEnable:
    class: ../../../Contexts/UserRecord/application/Enable/UserRecordEnable
    arguments: ['@UserRecord.UserRecordRepository']

  UserRecord.UserRecordEnableCommandHandler:
    class: ../../../Contexts/UserRecord/application/Enable/UserRecordEnableCommandHandler
    arguments: ['@UserRecord.UserRecordEnable']
    tags:
      - { name: 'commandHandler' }

  UserRecord.UserRecordEnableController:
    class: ../../../Apps/UserRecord/controllers/UserRecordEnableController
    arguments: ['@Shared.CommandBus']

  UserRecord.UserRecordDisable:
    class: ../../../Contexts/UserRecord/application/Disable/UserRecordDisable
    arguments: ['@UserRecord.UserRecordRepository']

  UserRecord.UserRecordDisableCommandHandler:
    class: ../../../Contexts/UserRecord/application/Disable/UserRecordDisableCommandHandler
    arguments: ['@UserRecord.UserRecordDisable']
    tags:
      - { name: 'commandHandler' }

  UserRecord.UserRecordDisableController:
    class: ../../../Apps/UserRecord/controllers/UserRecordDisableController
    arguments: ['@Shared.CommandBus']

  UserRecord.UserRecordResetPassword:
    class: ../../../Contexts/UserRecord/application/ResetPassword/UserRecordResetPassword
    arguments: ['@UserRecord.UserRecordRepository']
  
  UserRecord.UserRecordResetPasswordCommandHandler:
    class: ../../../Contexts/UserRecord/application/ResetPassword/UserRecordResetPasswordCommandHandler
    arguments: ['@UserRecord.UserRecordResetPassword']
    tags:
      - { name: 'commandHandler' }

  UserRecord.UserRecordResetPasswordController:
    class: ../../../Apps/UserRecord/controllers/UserRecordResetPasswordController
    arguments: ['@Shared.CommandBus']