services:
  UserRecord.UserRecordRepository:
    class: ../../../Contexts/UserRecord/infrastructure/UserRecordRepositoryFirebase
    arguments: []

  UserRecord.UserRecordCreate:
    class: ../../../Contexts/UserRecord/application/create/UserRecordCreate
    arguments: ['@UserRecord.UserRecordRepository']

  UserRecord.UserRecordProfile:
    class: ../../../Contexts/UserRecord/application/profile/UserRecordProfile
    arguments: ['@UserRecord.UserRecordRepository']

